server:
  servlet:
    context-path: /main_api/v1
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${KOKO_MAIN_DB_HOST}:${KOKO_MAIN_DB_PORT}/${KOKO_MAIN_DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${KOKO_MAIN_DB_USER}
    password: ${KOKO_MAIN_DB_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: prod
